# Generated by Django 4.2.1 on 2023-05-26 04:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Screening",
            fields=[
                (
                    "screening_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("time", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Theater",
            fields=[
                (
                    "theater_id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("theater_name", models.CharField(max_length=50)),
                ("theater_genre", models.CharField(max_length=20)),
                ("playtime", models.CharField(max_length=20)),
                ("price", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                ("seat_id", models.IntegerField(primary_key=True, serialize=False)),
                ("seat_number", models.IntegerField()),
                ("status", models.BooleanField()),
                (
                    "screening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.screening",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="screening",
            name="theater",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="booking.theater"
            ),
        ),
        migrations.CreateModel(
            name="Booking",
            fields=[
                ("booking_id", models.IntegerField(primary_key=True, serialize=False)),
                ("seat_number", models.IntegerField()),
                ("phone_number", models.CharField(max_length=20)),
                (
                    "screening",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="booking.screening",
                    ),
                ),
            ],
        ),
    ]
